#!/usr/bin/env python3
"""
Generate simdunalignedbitpacking_u16.cpp — SIMD unaligned bit-packing for uint16.

Mirrors simdunalignedbitpacking_new.cpp but for 16-bit lanes.

Usage:
  gen_simdunalignedbitpacking_u16.py [--mode {fused,normal,guarded}]

  fused   — unpack only accumulates sum; no output writes (original behaviour)
  normal  — unpack writes output; no sum accumulation
  guarded — (default) unpack behaviour controlled at compile time via
             #ifdef SIMD_SUM_FUSED: defined → fused, undefined → normal
"""

import argparse

BLOCK = 128        # values per block (same as 32-bit)
LANES = 8          # uint16 values per __m128i
LANE_BITS = 16     # bits per lane
MAX_BIT = 16       # maximum bit width


def gen_header(mode):
    mode_comment = {
        'fused':   ' * Unpack mode: FUSED — sum only, no output writes.',
        'normal':  ' * Unpack mode: NORMAL — output writes, no sum accumulation.',
        'guarded': ' * Unpack mode: GUARDED — compile-time toggle via SIMD_SUM_FUSED.\n'
                   ' *   #define SIMD_SUM_FUSED  → fused (sum only)\n'
                   ' *   (undefined)             → normal (output writes)',
    }[mode]
    aggregate = ""
    if mode != 'normal':
        aggregate = """
static inline void aggregate_sums_u16(__m128i OutReg, __m128i* sum) {
    // Zero-extend 8 x uint16 -> 4 x int32, then accumulate.
    // _mm_madd_epi16 treats inputs as signed — wrong for values > 32767.
    __m128i zero = _mm_setzero_si128();
    *sum = _mm_add_epi32(*sum, _mm_unpacklo_epi16(OutReg, zero));
    *sum = _mm_add_epi32(*sum, _mm_unpackhi_epi16(OutReg, zero));
}
"""
    return """\
/**
 * Auto-generated uint16 SIMD unaligned bit-packing/unpacking.
 * Generated by gen_simdunalignedbitpacking_u16.py --mode %(mode)s
 *
%(mode_comment)s
 *
 * This code is released under the
 * Apache License Version 2.0 http://www.apache.org/licenses/.
 */

#include "usimdbitpacking_u16.h"

namespace FastPForLib {

namespace simdunaligned_u16 {
%(aggregate)s
static void SIMD_nullunpacker16(const __m128i *__restrict__,
                                uint16_t *__restrict__) {
}

""" % {'mode': mode, 'mode_comment': mode_comment, 'aggregate': aggregate}


def gen_pack_function(bit):
    """Generate pack function for given bit width."""
    lines = []

    if bit == 0:
        lines.append("static void __SIMD_fastpackwithoutmask0_16(const uint16_t *__restrict__, __m128i *__restrict__) {")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append("static void __SIMD_fastpackwithoutmask%d_16(const uint16_t *__restrict__ _in," % bit)
    lines.append("                                           __m128i *__restrict__ out) {")
    lines.append("  const __m128i *in = reinterpret_cast<const __m128i *>(_in);")

    if bit == LANE_BITS:
        lines.append("  for (int i = 0; i < %d; ++i) {" % (BLOCK // LANES))
        lines.append("    _mm_storeu_si128(out + i, _mm_loadu_si128(in + i));")
        lines.append("  }")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append("  __m128i OutReg;")
    lines.append("  __m128i InReg = _mm_loadu_si128(in);")
    lines.append("")

    out_word = 0
    bit_pos = 0
    total_inputs = BLOCK // LANES  # 16

    lines.append("  OutReg = InReg;")
    bit_pos = bit

    for i in range(1, total_inputs):
        lines.append("  InReg = _mm_loadu_si128(++in);")
        remaining = LANE_BITS - bit_pos

        if remaining >= bit:
            if bit_pos == 0:
                lines.append("  OutReg = InReg;")
            else:
                lines.append("  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, %d));" % bit_pos)
            bit_pos += bit
        else:
            if remaining > 0:
                lines.append("  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, %d));" % bit_pos)
            lines.append("  _mm_storeu_si128(out++, OutReg);")
            if remaining > 0:
                lines.append("  OutReg = _mm_srli_epi16(InReg, %d);" % remaining)
            else:
                lines.append("  OutReg = InReg;")
            bit_pos = bit - remaining

        if bit_pos == LANE_BITS:
            lines.append("  _mm_storeu_si128(out++, OutReg);")
            bit_pos = 0

    if bit_pos > 0:
        lines.append("  _mm_storeu_si128(out++, OutReg);")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def emit_value(lines, mode):
    """Emit store, sum accumulation, or both with #ifdef guard."""
    if mode == 'fused':
        lines.append("  aggregate_sums_u16(OutReg, sum);")
    elif mode == 'normal':
        lines.append("  _mm_storeu_si128(reinterpret_cast<__m128i *>(out), OutReg);")
        lines.append("  out += 8;")
    else:  # guarded
        lines.append("#ifdef SIMD_SUM_FUSED")
        lines.append("  aggregate_sums_u16(OutReg, sum);")
        lines.append("#else")
        lines.append("  _mm_storeu_si128(reinterpret_cast<__m128i *>(out), OutReg);")
        lines.append("  out += 8;")
        lines.append("#endif")


def gen_unpack_function(bit, mode):
    """Generate unpack function for given bit width and mode."""
    if bit == 0:
        return ""

    has_sum = mode in ('fused', 'guarded')

    lines = []
    lines.append("static void __SIMD_fastunpack%d_16(const __m128i *__restrict__ in," % bit)
    lines.append("                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {")

    if mode == 'fused':
        lines.append("  (void)_out;")
    elif mode == 'normal':
        lines.append("  uint16_t *out = _out;")
        lines.append("  (void)sum;")
    else:  # guarded
        lines.append("#ifdef SIMD_SUM_FUSED")
        lines.append("  (void)_out;")
        lines.append("#else")
        lines.append("  uint16_t *out = _out;")
        lines.append("  (void)sum;")
        lines.append("#endif")

    lines.append("  __m128i InReg = _mm_loadu_si128(in);")

    if bit == LANE_BITS:
        # bit=16: each input __m128i IS 8 values
        if has_sum:
            lines.append("#ifdef SIMD_SUM_FUSED" if mode == 'guarded' else "")
            lines.append("  aggregate_sums_u16(InReg, sum);")
            for i in range(1, BLOCK // LANES):
                lines.append("  InReg = _mm_loadu_si128(++in);")
                lines.append("  aggregate_sums_u16(InReg, sum);")
            if mode == 'guarded':
                lines.append("#else")
                lines.append("  _mm_storeu_si128(reinterpret_cast<__m128i *>(out), InReg);")
                lines.append("  out += 8;")
                for i in range(1, BLOCK // LANES):
                    lines.append("  InReg = _mm_loadu_si128(++in);")
                    lines.append("  _mm_storeu_si128(reinterpret_cast<__m128i *>(out), InReg);")
                    lines.append("  out += 8;")
                lines.append("#endif")
        else:
            lines.append("  _mm_storeu_si128(reinterpret_cast<__m128i *>(out), InReg);")
            lines.append("  out += 8;")
            for i in range(1, BLOCK // LANES):
                lines.append("  InReg = _mm_loadu_si128(++in);")
                lines.append("  _mm_storeu_si128(reinterpret_cast<__m128i *>(out), InReg);")
                lines.append("  out += 8;")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append("  __m128i OutReg;")
    lines.append("  const __m128i mask = _mm_set1_epi16((1U << %d) - 1);" % bit)
    lines.append("")

    bit_pos = 0
    total_values = BLOCK // LANES  # 16

    for v in range(total_values):
        remaining = LANE_BITS - bit_pos

        if remaining >= bit:
            if bit_pos == 0:
                lines.append("  OutReg = _mm_and_si128(InReg, mask);")
            else:
                lines.append("  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, %d), mask);" % bit_pos)
            emit_value(lines, mode)
            lines.append("")
            bit_pos += bit
        else:
            if remaining > 0:
                lines.append("  OutReg = _mm_srli_epi16(InReg, %d);" % bit_pos)
            lines.append("  InReg = _mm_loadu_si128(++in);")
            need = bit - remaining
            if remaining > 0:
                lines.append("  OutReg =")
                lines.append("      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, %d - %d), mask));" % (bit, need))
            else:
                lines.append("  OutReg = _mm_and_si128(InReg, mask);")
            emit_value(lines, mode)
            lines.append("")
            bit_pos = need

        if bit_pos == LANE_BITS:
            if v < total_values - 1:
                lines.append("  InReg = _mm_loadu_si128(++in);")
            bit_pos = 0

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_dispatchers():
    lines = []

    # Pack dispatcher
    lines.append("} // namespace simdunaligned_u16")
    lines.append("")
    lines.append("void usimdpack_u16(const uint16_t *__restrict__ in, __m128i *__restrict__ out,")
    lines.append("                   const uint32_t bit) {")
    lines.append("  using namespace simdunaligned_u16;")
    lines.append("  switch (bit) {")
    for b in range(MAX_BIT + 1):
        lines.append("  case %d:" % b)
        lines.append("    __SIMD_fastpackwithoutmask%d_16(in, out);" % b)
        lines.append("    return;")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    # Unpack dispatcher
    lines.append("void usimdunpack_u16(const __m128i *__restrict__ in, uint16_t *__restrict__ out,")
    lines.append("                     const uint32_t bit, __m128i *__restrict__ sum) {")
    lines.append("  using namespace simdunaligned_u16;")
    lines.append("  switch (bit) {")
    lines.append("  case 0:")
    lines.append("    SIMD_nullunpacker16(in, out);")
    lines.append("    return;")
    for b in range(1, MAX_BIT + 1):
        lines.append("  case %d:" % b)
        lines.append("    __SIMD_fastunpack%d_16(in, out, sum);" % b)
        lines.append("    return;")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace FastPForLib")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description='Generate simdunalignedbitpacking_u16.cpp')
    parser.add_argument(
        '--mode', choices=['fused', 'normal', 'guarded'], default='guarded',
        help='fused: sum only; normal: output writes; guarded: #ifdef SIMD_SUM_FUSED (default)')
    args = parser.parse_args()
    mode = args.mode

    out = []
    out.append(gen_header(mode))

    for bit in range(MAX_BIT + 1):
        out.append(gen_pack_function(bit))

    for bit in range(1, MAX_BIT + 1):
        out.append(gen_unpack_function(bit, mode))

    out.append(gen_dispatchers())
    print("".join(out))


if __name__ == "__main__":
    main()
