#!/usr/bin/env python3
"""
Generate simdunalignedbitpacking_u16.cpp — SIMD unaligned bit-packing for uint16,
with fused sum aggregation (no output writes during unpack).

Supports 128-bit (AVX) and 256-bit (AVX2) register widths.

Usage:
  python gen_simdunalignedbitpacking_u16.py --width 128   # AVX (128-bit registers)
  python gen_simdunalignedbitpacking_u16.py --width 256   # AVX2 (256-bit registers)
"""
import argparse
import os
import sys

LANE_BITS = 16
MAX_BIT = 16


def intrinsics(width):
    """Return a dict of intrinsic names for the given register width."""
    if width == 128:
        return dict(
            reg='__m128i',
            load='_mm_loadu_si128',
            store='_mm_storeu_si128',
            setzero='_mm_setzero_si128',
            or_fn='_mm_or_si128',
            and_fn='_mm_and_si128',
            slli='_mm_slli_epi16',
            srli='_mm_srli_epi16',
            set1='_mm_set1_epi16',
            add='_mm_add_epi32',
            unpacklo='_mm_unpacklo_epi16',
            unpackhi='_mm_unpackhi_epi16',
        )
    else:
        return dict(
            reg='__m256i',
            load='_mm256_loadu_si256',
            store='_mm256_storeu_si256',
            setzero='_mm256_setzero_si256',
            or_fn='_mm256_or_si256',
            and_fn='_mm256_and_si256',
            slli='_mm256_slli_epi16',
            srli='_mm256_srli_epi16',
            set1='_mm256_set1_epi16',
            add='_mm256_add_epi32',
            unpacklo='_mm256_unpacklo_epi16',
            unpackhi='_mm256_unpackhi_epi16',
        )


def gen_header(I):
    return f"""\
/**
 * Auto-generated uint16 SIMD unaligned bit-packing with fused sum aggregation.
 * Generated by gen_simdunalignedbitpacking_u16.py (width={I['width']})
 *
 * This code is released under the
 * Apache License Version 2.0 http://www.apache.org/licenses/.
 */

#include "usimdbitpacking_u16.h"

namespace FastPForLib {{

namespace simdunaligned_u16 {{

static const {I['reg']} kZero = {I['setzero']}();

static inline void aggregate_sums_u16({I['reg']} OutReg, {I['reg']}* sum) {{
    // Zero-extend uint16 -> int32, then accumulate.
    *sum = {I['add']}(*sum, {I['unpacklo']}(OutReg, kZero));
    *sum = {I['add']}(*sum, {I['unpackhi']}(OutReg, kZero));
}}

static void SIMD_nullunpacker16(const {I['reg']} *__restrict__,
                                uint16_t *__restrict__) {{
}}

"""


def gen_pack_function(bit, I):
    """Generate pack function for given bit width."""
    lines = []
    lanes = I['lanes']
    block = I['block']
    total_inputs = block // lanes

    if bit == 0:
        lines.append(f"static void __SIMD_fastpackwithoutmask0_16("
                     f"const uint16_t *__restrict__, {I['reg']} *__restrict__) {{")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append(f"static void __SIMD_fastpackwithoutmask{bit}_16("
                 f"const uint16_t *__restrict__ _in,")
    lines.append(f"    {I['reg']} *__restrict__ out) {{")
    lines.append(f"  const {I['reg']} *in = reinterpret_cast<const {I['reg']} *>(_in);")

    if bit == LANE_BITS:
        lines.append(f"  for (int i = 0; i < {total_inputs}; ++i) {{")
        lines.append(f"    {I['store']}(out + i, {I['load']}(in + i));")
        lines.append("  }")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append(f"  {I['reg']} OutReg;")
    lines.append(f"  {I['reg']} InReg = {I['load']}(in);")
    lines.append("")

    bit_pos = 0
    lines.append("  OutReg = InReg;")
    bit_pos = bit

    for i in range(1, total_inputs):
        lines.append(f"  InReg = {I['load']}(++in);")
        remaining = LANE_BITS - bit_pos

        if remaining >= bit:
            if bit_pos == 0:
                lines.append("  OutReg = InReg;")
            else:
                lines.append(f"  OutReg = {I['or_fn']}(OutReg, {I['slli']}(InReg, {bit_pos}));")
            bit_pos += bit
        else:
            if remaining > 0:
                lines.append(f"  OutReg = {I['or_fn']}(OutReg, {I['slli']}(InReg, {bit_pos}));")
            lines.append(f"  {I['store']}(out++, OutReg);")
            if remaining > 0:
                lines.append(f"  OutReg = {I['srli']}(InReg, {remaining});")
            else:
                lines.append("  OutReg = InReg;")
            bit_pos = bit - remaining

        if bit_pos == LANE_BITS:
            lines.append(f"  {I['store']}(out++, OutReg);")
            bit_pos = 0

    if bit_pos > 0:
        lines.append(f"  {I['store']}(out++, OutReg);")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_unpack_function(bit, I):
    """Generate fused unpack+sum function for given bit width."""
    lines = []
    lanes = I['lanes']
    block = I['block']
    total_values = block // lanes

    if bit == 0:
        return ""

    lines.append(f"static void __SIMD_fastunpack{bit}_16("
                 f"const {I['reg']} *__restrict__ in,")
    lines.append(f"    uint16_t *__restrict__ _out, {I['reg']} *__restrict__ sum) {{")
    lines.append("  (void)_out;")
    lines.append(f"  {I['reg']} InReg = {I['load']}(in);")

    if bit == LANE_BITS:
        lines.append("  aggregate_sums_u16(InReg, sum);")
        for i in range(1, total_values):
            lines.append(f"  InReg = {I['load']}(++in);")
            lines.append("  aggregate_sums_u16(InReg, sum);")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    lines.append(f"  {I['reg']} OutReg;")
    lines.append(f"  const {I['reg']} mask = {I['set1']}((1U << {bit}) - 1);")
    lines.append("")

    bit_pos = 0

    for v in range(total_values):
        remaining = LANE_BITS - bit_pos

        if remaining >= bit:
            if bit_pos == 0:
                lines.append(f"  OutReg = {I['and_fn']}(InReg, mask);")
            else:
                lines.append(f"  OutReg = {I['and_fn']}({I['srli']}(InReg, {bit_pos}), mask);")
            lines.append("  aggregate_sums_u16(OutReg, sum);")
            lines.append("")
            bit_pos += bit
        else:
            if remaining > 0:
                lines.append(f"  OutReg = {I['srli']}(InReg, {bit_pos});")
            lines.append(f"  InReg = {I['load']}(++in);")
            need = bit - remaining
            if remaining > 0:
                lines.append(f"  OutReg =")
                lines.append(f"      {I['or_fn']}(OutReg, {I['and_fn']}({I['slli']}(InReg, {bit} - {need}), mask));")
            else:
                lines.append(f"  OutReg = {I['and_fn']}(InReg, mask);")
            lines.append("  aggregate_sums_u16(OutReg, sum);")
            lines.append("")
            bit_pos = need

        if bit_pos == LANE_BITS:
            if v < total_values - 1:
                lines.append(f"  InReg = {I['load']}(++in);")
            bit_pos = 0

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_dispatchers(I):
    lines = []

    # Pack dispatcher
    lines.append("} // namespace simdunaligned_u16")
    lines.append("")
    lines.append(f"void usimdpack_u16(const uint16_t *__restrict__ in, {I['reg']} *__restrict__ out,")
    lines.append(f"                   const uint32_t bit) {{")
    lines.append("  using namespace simdunaligned_u16;")
    lines.append("  switch (bit) {")
    for b in range(MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastpackwithoutmask{b}_16(in, out);")
        lines.append("    return;")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    # Unpack dispatcher
    lines.append(f"void usimdunpack_u16(const {I['reg']} *__restrict__ in, uint16_t *__restrict__ out,")
    lines.append(f"                     const uint32_t bit, {I['reg']} *__restrict__ sum) {{")
    lines.append("  using namespace simdunaligned_u16;")
    lines.append("  switch (bit) {")
    lines.append("  case 0:")
    lines.append("    SIMD_nullunpacker16(in, out);")
    lines.append("    return;")
    for b in range(1, MAX_BIT + 1):
        lines.append(f"  case {b}:")
        lines.append(f"    __SIMD_fastunpack{b}_16(in, out, sum);")
        lines.append("    return;")
    lines.append("  default:")
    lines.append("    break;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace FastPForLib")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description='Generate SIMD unaligned bit-packing for uint16')
    parser.add_argument('--width', type=int, choices=[128, 256], default=128,
                        help='Register width in bits (128=AVX, 256=AVX2)')
    args = parser.parse_args()

    I = intrinsics(args.width)
    lanes = args.width // LANE_BITS
    block = lanes * MAX_BIT
    I['lanes'] = lanes
    I['block'] = block
    I['width'] = args.width

    out = []
    out.append(gen_header(I))

    for bit in range(MAX_BIT + 1):
        out.append(gen_pack_function(bit, I))

    for bit in range(1, MAX_BIT + 1):
        out.append(gen_unpack_function(bit, I))

    out.append(gen_dispatchers(I))

    script_dir = os.path.dirname(os.path.abspath(__file__))
    src_dir = os.path.join(script_dir, '..', 'src')
    out_path = os.path.join(src_dir, 'simdunalignedbitpacking_u16.cpp')

    with open(out_path, 'w') as f:
        f.write("".join(out))
    print(f"Generated {out_path}")


if __name__ == "__main__":
    main()
