/**
 * Auto-generated uint16 SIMD unaligned bit-packing with fused sum aggregation.
 * Generated by gen_simdunalignedbitpacking_u16.py
 *
 * This code is released under the
 * Apache License Version 2.0 http://www.apache.org/licenses/.
 */

#include "usimdbitpacking_u16.h"

namespace FastPForLib {

namespace simdunaligned_u16 {

static inline void aggregate_sums_u16(__m128i OutReg, __m128i* sum) {
    // Zero-extend 8 x uint16 -> 4 x int32, then accumulate.
    // _mm_madd_epi16 treats inputs as signed — wrong for values > 32767.
    __m128i zero = _mm_setzero_si128();
    *sum = _mm_add_epi32(*sum, _mm_unpacklo_epi16(OutReg, zero));
    *sum = _mm_add_epi32(*sum, _mm_unpackhi_epi16(OutReg, zero));
}

static void SIMD_nullunpacker16(const __m128i *__restrict__,
                                uint16_t *__restrict__) {
}

static void __SIMD_fastpackwithoutmask0_16(const uint16_t *__restrict__, __m128i *__restrict__) {
}
static void __SIMD_fastpackwithoutmask1_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask2_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask3_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 1);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask4_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask5_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 1);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 3);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask6_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask7_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 1);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 3);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 5);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask8_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask9_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 7);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 5);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 3);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 1);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask10_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask11_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 5);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 9);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 3);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 7);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 1);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask12_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask13_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 3);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 9);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 5);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 11);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 1);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 7);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask14_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  _mm_storeu_si128(out++, OutReg);
  InReg = _mm_loadu_si128(++in);
  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask15_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  __m128i OutReg;
  __m128i InReg = _mm_loadu_si128(in);

  OutReg = InReg;
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 15));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 1);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 14));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 13));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 3);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 12));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 11));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 5);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 10));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 9));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 7);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 8));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 7));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 9);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 6));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 5));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 11);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 4));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 3));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 13);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 2));
  _mm_storeu_si128(out++, OutReg);
  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_or_si128(OutReg, _mm_slli_epi16(InReg, 1));
  _mm_storeu_si128(out++, OutReg);
}
static void __SIMD_fastpackwithoutmask16_16(const uint16_t *__restrict__ _in,
                                           __m128i *__restrict__ out) {
  const __m128i *in = reinterpret_cast<const __m128i *>(_in);
  for (int i = 0; i < 16; ++i) {
    _mm_storeu_si128(out + i, _mm_loadu_si128(in + i));
  }
}
static void __SIMD_fastunpack1_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 1) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 3), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 5), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 7), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 9), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 10), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 11), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 13), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 14), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 15), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack2_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 2) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 10), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 14), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 10), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 14), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack3_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 3) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 3), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 9), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 15);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 3 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 5), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 11), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 3 - 1), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 7), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 10), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 13), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack4_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 4) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 12), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack5_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 5) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 5), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 10), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 15);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 5 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 9), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 5 - 3), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 3), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 13);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 5 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 7), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 5 - 1), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 11), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack6_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 6) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 6 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 6 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 10), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 6 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 6 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 10), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack7_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 7) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 7), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 7 - 5), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 5), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 7 - 3), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 3), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 7 - 1), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 15);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 7 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 13);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 7 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 11);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 7 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 9), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack8_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 8) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 8), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack9_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 9) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 9);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 11);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 13);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 15);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 1), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 3), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 3), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 5), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 5), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 9 - 7), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 7), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack10_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 10) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 10 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 6), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack11_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 11) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 11);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 1), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 7), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 7);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 13);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 3), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 3), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 9), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 9);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 15);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 10), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 11 - 5), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 5), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack12_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 12) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 12 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 4), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack13_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 13) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 13);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 10), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 7), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 7);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 1), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 11), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 11);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 5), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 5);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 15);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 12), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 9), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 9);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 13 - 3), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 3), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack14_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 14) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 12), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 10), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

  InReg = _mm_loadu_si128(++in);
  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 12), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 10), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 14 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 2), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack15_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  __m128i OutReg;
  const __m128i mask = _mm_set1_epi16((1U << 15) - 1);

  OutReg = _mm_and_si128(InReg, mask);
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 15);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 14), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 14);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 13), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 13);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 12), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 12);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 11), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 11);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 10), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 10);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 9), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 9);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 8), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 8);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 7), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 7);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 6), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 6);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 5), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 5);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 4), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 4);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 3), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 3);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 2), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_srli_epi16(InReg, 2);
  InReg = _mm_loadu_si128(++in);
  OutReg =
      _mm_or_si128(OutReg, _mm_and_si128(_mm_slli_epi16(InReg, 15 - 1), mask));
  aggregate_sums_u16(OutReg, sum);

  OutReg = _mm_and_si128(_mm_srli_epi16(InReg, 1), mask);
  aggregate_sums_u16(OutReg, sum);

}
static void __SIMD_fastunpack16_16(const __m128i *__restrict__ in,
                                   uint16_t *__restrict__ _out, __m128i *__restrict__ sum) {
  (void)_out;
  __m128i InReg = _mm_loadu_si128(in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
  InReg = _mm_loadu_si128(++in);
  aggregate_sums_u16(InReg, sum);
}
} // namespace simdunaligned_u16

void usimdpack_u16(const uint16_t *__restrict__ in, __m128i *__restrict__ out,
                   const uint32_t bit) {
  using namespace simdunaligned_u16;
  switch (bit) {
  case 0:
    __SIMD_fastpackwithoutmask0_16(in, out);
    return;
  case 1:
    __SIMD_fastpackwithoutmask1_16(in, out);
    return;
  case 2:
    __SIMD_fastpackwithoutmask2_16(in, out);
    return;
  case 3:
    __SIMD_fastpackwithoutmask3_16(in, out);
    return;
  case 4:
    __SIMD_fastpackwithoutmask4_16(in, out);
    return;
  case 5:
    __SIMD_fastpackwithoutmask5_16(in, out);
    return;
  case 6:
    __SIMD_fastpackwithoutmask6_16(in, out);
    return;
  case 7:
    __SIMD_fastpackwithoutmask7_16(in, out);
    return;
  case 8:
    __SIMD_fastpackwithoutmask8_16(in, out);
    return;
  case 9:
    __SIMD_fastpackwithoutmask9_16(in, out);
    return;
  case 10:
    __SIMD_fastpackwithoutmask10_16(in, out);
    return;
  case 11:
    __SIMD_fastpackwithoutmask11_16(in, out);
    return;
  case 12:
    __SIMD_fastpackwithoutmask12_16(in, out);
    return;
  case 13:
    __SIMD_fastpackwithoutmask13_16(in, out);
    return;
  case 14:
    __SIMD_fastpackwithoutmask14_16(in, out);
    return;
  case 15:
    __SIMD_fastpackwithoutmask15_16(in, out);
    return;
  case 16:
    __SIMD_fastpackwithoutmask16_16(in, out);
    return;
  default:
    break;
  }
}

void usimdunpack_u16(const __m128i *__restrict__ in, uint16_t *__restrict__ out,
                     const uint32_t bit, __m128i *__restrict__ sum) {
  using namespace simdunaligned_u16;
  switch (bit) {
  case 0:
    SIMD_nullunpacker16(in, out);
    return;
  case 1:
    __SIMD_fastunpack1_16(in, out, sum);
    return;
  case 2:
    __SIMD_fastunpack2_16(in, out, sum);
    return;
  case 3:
    __SIMD_fastunpack3_16(in, out, sum);
    return;
  case 4:
    __SIMD_fastunpack4_16(in, out, sum);
    return;
  case 5:
    __SIMD_fastunpack5_16(in, out, sum);
    return;
  case 6:
    __SIMD_fastunpack6_16(in, out, sum);
    return;
  case 7:
    __SIMD_fastunpack7_16(in, out, sum);
    return;
  case 8:
    __SIMD_fastunpack8_16(in, out, sum);
    return;
  case 9:
    __SIMD_fastunpack9_16(in, out, sum);
    return;
  case 10:
    __SIMD_fastunpack10_16(in, out, sum);
    return;
  case 11:
    __SIMD_fastunpack11_16(in, out, sum);
    return;
  case 12:
    __SIMD_fastunpack12_16(in, out, sum);
    return;
  case 13:
    __SIMD_fastunpack13_16(in, out, sum);
    return;
  case 14:
    __SIMD_fastunpack14_16(in, out, sum);
    return;
  case 15:
    __SIMD_fastunpack15_16(in, out, sum);
    return;
  case 16:
    __SIMD_fastunpack16_16(in, out, sum);
    return;
  default:
    break;
  }
}

} // namespace FastPForLib

